webtalk_init -webtalk_dir /home/liuh0f/pro0423/pro1/pro1.sim/sim_1/behav/xsim/xsim.dir/all_brick_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 24 01:42:54 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887999_1777552194_210720986_228" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a3d77e80-2f36-4e91-977c-da8d5d52b0e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e45be7f0c1314d72ba24392b21312c98" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-4627 v4 @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.242 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "540.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "55373575 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "16.29_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "120080_KB" -context "xsim\\usage"
webtalk_transmit -clientid 435169683 -regid "211887999_1777552194_210720986_228" -xml /home/liuh0f/pro0423/pro1/pro1.sim/sim_1/behav/xsim/xsim.dir/all_brick_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/liuh0f/pro0423/pro1/pro1.sim/sim_1/behav/xsim/xsim.dir/all_brick_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/liuh0f/pro0423/pro1/pro1.sim/sim_1/behav/xsim/xsim.dir/all_brick_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
